version: '3'
services:
    broker:
        build: broker
    auldfellas:
        build: auldfellas
        environment: 
            HOST: broker
        depends_on:
        - broker
    dodgydrivers:
        build: dodgydrivers
        environment: 
            HOST: broker
        depends_on:
        - broker
    girlpower:
        build: girlpower
        environment: 
            HOST: broker
        depends_on:
        - broker
    client:
        build: client
        environment: 
            HOST: broker
        depends_on:
        - broker
        - auldfellas
        - dodgydrivers
        - girlpower
